# 210329

### FilterSet 내에서 Try/Except 구문 사용 시 주의

-   Custom FilterSet에서 Ordering 기능을 구현

    -   ex: id로 오름차순('id') 또는 내림차순('-id')를 실행할 수 있어야함
    -   만약, 모델에 없는 필드값이 들어올 경우 예외처리를 할 수 있어야함

    ```python
    class PrescriptionFilter(FilterSet):
        def filter_ordering(self, queryset, name, value):
            try:
                ordered_queryset = queryset.order_by(value)
            except Exception as e:
                raise ValidationError(e)
            return ordered_queryse
    ```

-   위 구문에서 ValidationError가 실행되지 못하고 반복적으로 django exception(django.core.exceptions.FieldError: Cannot resolve keyword 'idd' into field....)이 발생

### 원인

-   Filterset 메서드 내에서 queryset이 직접 실행되지 않음
    -   queryset은 lazy evaluation이므로 실제로 사용되기 전 까지 쿼리문(ORM)이 실행되지 않음
-   따라서 위 필터 메서드에서는 쿼리문이 실행되지 않다가 화면에 출력되어야 할 때 (serializer의 to_representation 또는 그 전 과정중) 실행되기 때문에 에러를 검출하지 못함



### 해결(지양)

```python
class PrescriptionFilter(FilterSet):
    def filter_ordering(self, queryset: QuerySet, name: str, value: str) -> QuerySet:
        self._validate_query_param(value)
        ordered_queryset = queryset.order_by(value)
        return ordered_queryset

    def _validate_query_param(self, value: str) -> NoReturn:
        field_name_list = []
        for field in self.queryset.model._meta.fields:
            field_name_list.append(field.name)
        if value[1:] in field_name_list or value in field_name_list:
            pass
        else:
            raise ValidationError(f"can not use '{value}' at ordering param")
```

-   입력값의 첫 글자('-') 이후 또는 입력한 전체 문자가 Model의 필드에 포함되어있는지 확인 
    -   True: order_by실행
    -   False: ValidationError 실행

-   Model._meta와 같이 protected member는 되도록 **사용하지 말아야 한다**.
    -   급한대로 구현했지만 나중에 꼭 수정할 예정

